dist: xenial

language: php

php:
  - 7.1
  - 7.2
  - 7.3

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - composer self-update

install:
  - composer install

script:
  - vendor/bin/phpunit

notifications:
  email: false